import { refs } from './js/refs';
import './js/api.js';
import './js/cards-fetch.js';
import './js/cards.js';
import './js/carousel.js';
import './js/library.js';
import './js/about-modal.js';
// import './js/movie-filters.js';
import './js/modalCards.js';
import './js/fetchMovieTrailer.js';
import './js/library-utils.js';
import './js/header.js';
import './js/hero-section.js';
import './js/createLibraryDOM.js';
import './js/library-modal.js';
import './js/handle-modal-btns.js';
import './js/locatStorage.js';
import './js/header.js';
import './js/cards-fetch-search.js';
